# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Truck.create(name: "The Cinnamon Snail", twitter_handle: "VeganLunchTruck")
Truck.create(name: "Korilla BBQ", twitter_handle: "KorillaBBQ")
Truck.create(name: "Phil's Steaks", twitter_handle: "PhilsSteaks")
Truck.create(name: "Milk Truck", twitter_handle: "milktrucknyc")

Truck.create(name: "Eddie's Pizza", twitter_handle: "EddiesPizzaNY")
Truck.create(name: "Red Hook Lobster Pound", twitter_handle: "lobstertruckny")
Truck.create(name: "Big Gay Ice Cream", twitter_handle: "biggayicecream")
Truck.create(name: "DUB Pies", twitter_handle: "dubpies")
Truck.create(name: "Taco Bite", twitter_handle: "tacobite")
Truck.create(name: "Carl's Steaks", twitter_handle: "carlssteaks")
Truck.create(name: "Wafels & Dinges", twitter_handle: "waffletruck")
Truck.create(name: "Mexicue", twitter_handle: "Mexicue")
Truck.create(name: "Coolhaus", twitter_handle: "CoolhausNY")
Truck.create(name: "Uncle Gussy's", twitter_handle: "UncleGussys")
Truck.create(name: "Souvlaki GR", twitter_handle: "souvlakitruck")
Truck.create(name: "Calexico", twitter_handle: "CalexicoNYC")
Truck.create(name: "Gorilla Cheese NYC", twitter_handle: "gcnyc1")
Truck.create(name: "Mamu Thai Noodle", twitter_handle: "mamuthainoodle")
Truck.create(name: "Toum NYC", twitter_handle: "ToumNYC")
Truck.create(name: "Taim Falafel", twitter_handle: "TaimMobile")
Truck.create(name: "Green Pirate Juice", twitter_handle: "juicepirate")
Truck.create(name: "Solber Pupusas", twitter_handle: "solberpupusas")
Truck.create(name: "Nuchas", twitter_handle: "NuchasNYC")
Truck.create(name: "Domo Taco", twitter_handle: "DomoTaco")
Truck.create(name: "Kimchi Taco", twitter_handle: "KimchiTruck")
Truck.create(name: "Kelvin Natural Slush", twitter_handle: "KELVINSLUSH")
Truck.create(name: "Sweet Chili NYC", twitter_handle: "SweetChiliNYC")
Truck.create(name: "Andy's Italian Ices", twitter_handle: "AndysItalianIce")
Truck.create(name: "Mike n Willie's", twitter_handle: "mikenwillies")
Truck.create(name: "Carpe Donut NYC", twitter_handle: "CarpeDonutNYC")
Truck.create(name: "The Treats Truck", twitter_handle: "TheTreatsTruck")
Truck.create(name: "Mr Nice Guy", twitter_handle: "MrNiceGuyTruck")
Truck.create(name: "The Treats Truck", twitter_handle: "TheTreatsTruck")
Truck.create(name: "Langos Truck", twitter_handle: "LangosTruck")
Truck.create(name: "Bian Dang", twitter_handle: "biandangnyc")
Truck.create(name: "Shortys NYC", twitter_handle: "shortysnyc")
Truck.create(name: "Mysttik Masaala", twitter_handle: "MysttikMasaala")
Truck.create(name: "Comme Ci, Comme Ça", twitter_handle: "Chefsamirtruck")
Truck.create(name: "The Munchie Mobile", twitter_handle: "MunchieMobileNY")
Truck.create(name: "Big D's Grub", twitter_handle: "@bigdsgrub")
Truck.create(name: "Brothers Express", twitter_handle: "BrothersExpress")
Truck.create(name: "Chipsy King", twitter_handle: "ChipsyKingNY")
Truck.create(name: "Crepes Truck", twitter_handle: "TheCrepesTruck")
Truck.create(name: "Desi Food Truck", twitter_handle: "DesiFoodTruck")
Truck.create(name: "Crif Dogs", twitter_handle: "CrifDogs")
Truck.create(name: "El Diablo Tacos", twitter_handle: "ElDiabloTacos")
Truck.create(name: "El Paso Truck", twitter_handle: "ElPasoTruck")
Truck.create(name: "Fresh and Hearty", twitter_handle: "FreshandHearty")
Truck.create(name: "Frites'n'Meats", twitter_handle: "fritesnmeats")
Truck.create(name: "GO Burger Truck", twitter_handle: "GOBurger")
Truck.create(name: "The Green Radish", twitter_handle: "thegreenradish1")
Truck.create(name: "Grill On Wheels", twitter_handle: "GrillOnWheelsNY")
Truck.create(name: "Hibachi Heaven", twitter_handle: "hibachiheaven")
Truck.create(name: "Jiannetto's Pizza", twitter_handle: "JiannettosPizza")
Truck.create(name: "Mexico Blvd.", twitter_handle: "MexicoBlvd")
Truck.create(name: "Miami Food Machine", twitter_handle: "MiamiMachineNYC")
Truck.create(name: "Palenque", twitter_handle: "Palenquefood")
Truck.create(name: "Seoul Food NYC", twitter_handle: "seoulfoodnyc")
Truck.create(name: "Shanghai Sogo", twitter_handle: "shanghaisogo")
Truck.create(name: "Shortys NYC", twitter_handle: "shortysnyc")
Truck.create(name: "Supreme Burger NYC", twitter_handle: "SupremeBurgerNY")
Truck.create(name: "The Squeeze Juice", twitter_handle: "TheSqueezeTruck")
Truck.create(name: "Tribeca Taco Truck", twitter_handle: "TribecaTaco")
Truck.create(name: "Trusty Burgers & Bites", twitter_handle: "trustytruck")
Truck.create(name: "Urban Lobster Shack", twitter_handle: "urbanlobster")
Truck.create(name: "Valduccis", twitter_handle: "Valduccis")
Truck.create(name: "XPL Halal Food", twitter_handle: "XplFood")
Truck.create(name: "La Bella Torte", twitter_handle: "LaBellaTorte")
Truck.create(name: "Rhong-Tiam", twitter_handle: "RhongTiam")
Truck.create(name: "XPL Halal Food", twitter_handle: "XplFood")
Truck.create(name: "The Frankfoota Truck", twitter_handle: "FrankfootaTruck")
Truck.create(name: "Sweetery", twitter_handle: "SweeteryNYC")
Truck.create(name: "The Steel Cart", twitter_handle: "TheSteelCart")
Truck.create(name: "Rickshaw Truck", twitter_handle: "rickshawtruck")
Truck.create(name: "Neapolitan Express", twitter_handle: "NeaExpress")
Truck.create(name: "Okadaman", twitter_handle: "OkadamanNYC")
Truck.create(name: "Fishing Shrimp", twitter_handle: "FishingShrimp")
Truck.create(name: "Itizy Ice Cream", twitter_handle: "ItizyIceCream")
Truck.create(name: "666 Burger", twitter_handle: "666burger")
Truck.create(name: "Cruisin' Kitchen", twitter_handle: "Cruisin_Kitchen")

Admin.create(username: "admin", password: "yolodbc")

# Tweet.create(truck_id: 1, body: "48 wall st", tweet_time: Time.now)
# Tweet.create(truck_id: 2, body: "32nd st & 5th ave", tweet_time: Time.now)
# Tweet.create(truck_id: 3, body: "990 avenue of america", tweet_time: Time.now)
# Tweet.create(truck_id: 4, body: "no way", tweet_time: Time.now)

